CREATE TABLE bookmarks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    RATING INTEGER NOT NULL,
    DESCRIPTION TEXT
)


/*
 title,
            url,
            rating,
            description,
            id
*/